### ISSUE TITLE
HUO3 - Consultar el listado de artistas

### ISSUE THREAD

**Issue by jj-chiroque** [misomazf88/MISW-4203-MobileApps-MJMJ#3]
**Como** usuario visitante **quiero** ver el listado de artistas **para** escoger lo que más me interesan
**Tareas**

- [x] #9
- [x] #10

**Criterios de Aceptación**

**Comment by MilenaCastilloC** [comment]
**Tareas**

- [ ] Configurar la vista para conocer el listado de los artistas.
- [ ] Configurar el servicio para obtener el listado de los artistas registrados en la aplicación, para que estos sean mostrados en la vista artistas.

**Criterios de Aceptación**
